version: '3.7'
services:
  # client:
  #   build: ./client
  #   container_name: starter_client
  #   ports:
  #     - 3000:3000
  #   working_dir: /client
  # server:
  #   image: node:16
  #   build: ./server
  #   working_dir: /app
  #   container_name: starter_server
  #   volumes:
  #     - $PWD/server:/app
  #   ports:
  #     - 8888:8888
  #   # command: "npm run dev"
  #   # tty: true
  db:
    image: mysql:8.0
    container_name: onboarding_db
    volumes:
      - ./framework/database/docker/logs:/var/log/mysql
      - ./framework/database/docker/data:/var/lib/mysql
      - ./framework/database/docker/conf/:/etc/mysql/conf.d
      - ./framework/database/:/docker-entrypoint-initdb.d
      # - ./database/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=onboarding
      - MYSQL_USER=levelenter
      - MYSQL_PASSWORD=levelenter
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306 
    restart: always
    tty: true
